---

# save report to local file, troubleshooting
- name: save result table to file
  ansible.builtin.copy:
    dest: ~/cis_rhel_results.json
    content: "{{ rules }}"
  delegate_to: localhost
  become: no
  when: save_report is defined

- name: rules
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ rules | flatten(levels=1) }}"

- name: set_fact results
  ansible.builtin.set_fact:
    results: "{{ results|default({})| combine( {item: rules[item]} ) }}"
  loop: "{{ rules | flatten(levels=1) }}"
  when: rules[item]['failed'] is defined

- name: all failed items
  ansible.builtin.debug: var=results
