---
# Preliminary tasks that should always be run
# List users in order to look files inside each home directory
- name: "PRELIM | List users accounts"
  ansible.builtin.command: "awk -F: '{print $1}' /etc/passwd"
  register: users
  changed_when: no
  check_mode: no

- name: "PRELIM | unset root password"
  ansible.builtin.shell: usermod -p "*" root
  changed_when: no
  check_mode: no

# fix it with: usermod -p "*" root
- name: "PRELIM | Gather accounts with empty password fields"
  # shell: "cat /etc/shadow | awk -F: '($2 == \"\" ) {j++;print $1; } END {exit j}'"
  ansible.builtin.shell: "cat /etc/shadow | awk -F: '($2 == \"\" ) {j++;print $1; } END {echo j}'"
  register: empty_password_accounts
  changed_when: no
  check_mode: no

- name: "PRELIM | Gather UID 0 accounts other than root"
  # shell: "cat /etc/passwd | awk -F: '($3 == 0 && $1 != \"root\") {i++;print $1 } END {exit i}'"
  ansible.builtin.shell: "cat /etc/passwd | awk -F: '($3 == 0 && $1 != \"root\") {i++;print $1 } END {echo i}'"
  register: uid_zero_accounts_except_root
  changed_when: no
  check_mode: no

- name: "PRELIM | Section 4.1 | Configure System Accounting (auditd)"
  ansible.builtin.yum:
    name: audit
    state: present

- name: "PRELIM | Section 5.1 | Configure cron"
  ansible.builtin.yum:
    name: cronie
    state: present

- name: "PRELIM | Check if prelink package is installed"
  ansible.builtin.command: rpm -q prelink
  args:
    warn: false # set warn=false to prevent warning
  register: prelink_installed
  changed_when: no
  failed_when: no
  check_mode: no
  tags:
    - skip_ansible_lint

- name: "PRELIM | Check if postfix package is installed"
  ansible.builtin.command: rpm -q postfix
  register: postfix_installed
  changed_when: no
  failed_when: no
  check_mode: no
  tags:
    - skip_ansible_lint

# Individual service checks
- name: "PRELIM | Check for xinetd service"
  ansible.builtin.shell: "systemctl show xinetd | grep LoadState | cut -d = -f 2"
  register: xinetd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for ntpd service"
  ansible.builtin.shell: "systemctl show ntpd | grep LoadState | cut -d = -f 2"
  register: ntpd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for chronyd service"
  ansible.builtin.shell: "systemctl show chronyd | grep LoadState | cut -d = -f 2"
  register: chronyd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for avahi-daemon service"
  ansible.builtin.shell: "systemctl show avahi-daemon | grep LoadState | cut -d = -f 2"
  register: avahi_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for cups service"
  ansible.builtin.shell: "systemctl show cups | grep LoadState | cut -d = -f 2"
  register: cups_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for dhcpd service"
  ansible.builtin.shell: "systemctl show dhcpd | grep LoadState | cut -d = -f 2"
  register: dhcpd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for slapd service"
  ansible.builtin.shell: "systemctl show slapd | grep LoadState | cut -d = -f 2"
  register: slapd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for nfs service"
  ansible.builtin.shell: "systemctl show nfs | grep LoadState | cut -d = -f 2"
  register: nfs_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for rpcbind service"
  ansible.builtin.shell: "systemctl show rpcbind | grep LoadState | cut -d = -f 2"
  register: rpcbind_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for named service"
  ansible.builtin.shell: "systemctl show named | grep LoadState | cut -d = -f 2"
  register: named_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for vsftpd service"
  ansible.builtin.shell: "systemctl show vsftpd | grep LoadState | cut -d = -f 2"
  register: vsftpd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for httpd service"
  ansible.builtin.shell: "systemctl show httpd | grep LoadState | cut -d = -f 2"
  register: httpd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for dovecot service"
  ansible.builtin.shell: "systemctl show dovecot | grep LoadState | cut -d = -f 2"
  register: dovecot_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for smb service"
  ansible.builtin.shell: "systemctl show smb | grep LoadState | cut -d = -f 2"
  register: smb_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for squid service"
  ansible.builtin.shell: "systemctl show squid | grep LoadState | cut -d = -f 2"
  register: squid_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for snmpd service"
  ansible.builtin.shell: "systemctl show snmpd | grep LoadState | cut -d = -f 2"
  register: snmpd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for ypserv service"
  ansible.builtin.shell: "systemctl show ypserv | grep LoadState | cut -d = -f 2"
  register: ypserv_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for rsh.socket service"
  ansible.builtin.shell: "systemctl show rsh.socket | grep LoadState | cut -d = -f 2"
  register: rsh_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for rlogin.socket service"
  ansible.builtin.shell: "systemctl show rlogin.socket | grep LoadState | cut -d = -f 2"
  register: rlogin_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for rexec.socket service"
  ansible.builtin.shell: "systemctl show rexec.socket | grep LoadState | cut -d = -f 2"
  register: rexec_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for telnet service"
  ansible.builtin.shell: "systemctl show telnet | grep LoadState | cut -d = -f 2"
  register: telnet_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for tftp service"
  ansible.builtin.shell: "systemctl show tftp | grep LoadState | cut -d = -f 2"
  register: tftp_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for rsyncd service"
  ansible.builtin.shell: "systemctl show rsyncd | grep LoadState | cut -d = -f 2"
  register: rsyncd_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for ntalk service"
  ansible.builtin.shell: "systemctl show ntalk | grep LoadState | cut -d = -f 2"
  register: ntalk_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for autofs service"
  ansible.builtin.shell: "systemctl show autofs | grep LoadState | cut -d = -f 2"
  register: autofs_service_status
  changed_when: no
  check_mode: no

- name: "PRELIM | Check for rhnsd service"
  ansible.builtin.shell: "systemctl show rhnsd | grep LoadState | cut -d = -f 2"
  register: rhnsd_service_status
  changed_when: no
  check_mode: no
