---
# handlers file for ansible-cis_rhel8-role


- name: grub_mkconfig
  become: yes
  ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: _restart_xinetd
  ansible.builtin.service:
    name: xinetd
    state: restarted

- name: _dconf_update
  ansible.builtin.shell: dconf update

- name: _reload_auditd
  ansible.builtin.shell: service auditd restart
#  ansible.builtin.service:
#    name: auditd
#    state: restarted

- name: restart_sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: sysctl_flush_ipv4_route_table
  become: yes
  ansible.builtin.sysctl:
    name: net.ipv4.route.flush
    value: 1
    sysctl_set: yes
  failed_when: false

- name: sysctl_flush_ipv6_route_table
  become: yes
  ansible.builtin.sysctl:
    name: net.ipv6.route.flush
    value: 1
    sysctl_set: yes
  failed_when: false
